spring:
  redis:
    port: 6379
    host: 127.0.0.1
    password: root
    timeout: 1000

    # 预定值，后期修改
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
      timeout: 1000
