server:
  port: 7001

spring:
  application:
    name: microservice-zuul-gateway #实例名称
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      # 单机版 Eureka 服务注册中心
      #defaultZone: http://localhost:6001/eureka
      # 集群版 Eureka 服务注册中心
      defaultZone: http://localhost:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true     #访问路径可以显示IP地址

zuul:
  routes:
    provider-member:    # 路由名称，名称任意，路由名称唯一
      path: /member/** # 访问路径
      serviceId: microservice-member # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀

    #人力资源
    provider-hr:
      path: /hr/**
      serviceId: microservice-member
      stripPrefix: false

    #社交主体
      provider-social:
        path: /social/**
        serviceId: microservice-social
        stripPrefix: false

    #直播
    provider-livevideo:
      path: /livevideo/**
      serviceId: microservice-livevideo
      stripPrefix: false

    #优惠
    provider-discount:
      path: /discount/**
      serviceId: microservice-discount
      stripPrefix: false

    #活动
    provider-activity:
      path: /activity/**
      serviceId: microservice-activity
      stripPrefix: false

    #广告
    provider-adver:
      path: /adver/**
      serviceId: microservice-adver
      stripPrefix: false

    #广告
    provider-comsumer:
      path: /comsumer/**
      serviceId: microservice-adver
      stripPrefix: false

    #金融
    provider-finacial:
      path: /financial/**
      serviceId:  provider-finacial
      stripPrefix: false





